static const int centbins[]={0,5,10,15,20,25,30,35,40,50,60,70,80,100};
TH1D * pt1A;
TH1D * pt1B;
TH1D * pt2A;
TH1D * pt2B;
TH1D * pt3A;
TH1D * pt3B;
TH1D * pt4A;
TH1D * pt4B;
TH1D * pt5A;
TH1D * pt5B;
TH1D * pt6A;
TH1D * pt6B;
TH1D * hold;
void CheckSymmetry(string file="../PbPb_262800_263230.root", string name="N3", int bin = 1){
  int maxptbin = 9;
  double zmin = -0.07;
  double zmax = 0.07;
  TFile * tf = new TFile(file.data(),"read");
  TH2D * qA = (TH2D *) tf->Get(Form("vnanalyzer/Harmonics/%d_%d/%s/qA",centbins[bin],centbins[bin+1],name.data()));
  TH2D * qB = (TH2D *) tf->Get(Form("vnanalyzer/Harmonics/%d_%d/%s/qB",centbins[bin],centbins[bin+1],name.data()));
  TH2D * wnA = (TH2D *) tf->Get(Form("vnanalyzer/Harmonics/%d_%d/%s/wnA",centbins[bin],centbins[bin+1],name.data()));
  TH2D * wnB = (TH2D *) tf->Get(Form("vnanalyzer/Harmonics/%d_%d/%s/wnB",centbins[bin],centbins[bin+1],name.data()));
  qA->Divide(wnA);
  qB->Divide(wnB);
  TCanvas * c = new TCanvas("c","c",1200,1000);
  c->Divide(3,2);
  c->cd(1);
  int ptbin = 2;
  pt1A = qA->ProjectionY("pt1A",ptbin,ptbin);
  pt1B = qB->ProjectionY("pt1B",ptbin,ptbin);
  hold = (TH1D *) pt1B->Clone("hold");
  for(int i = 1; i<=12; i++) {
    pt1B->SetBinContent(i,hold->GetBinContent(13-i));
    pt1B->SetBinError(i,hold->GetBinError(13-i));
  }
  hold->Delete();
  double av = 0;
  for(int i = 1; i<=12; i++) av+=pt1A->GetBinContent(i);
  for(int i = 1; i<=12; i++) av+=pt1B->GetBinContent(i);
  av/=24;
  pt1A->Scale(1./av);
  pt1A->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  pt1A->SetMinimum(0.8);
  pt1A->SetMaximum(1.2);
  pt1A->SetMarkerStyle(20);
  pt1A->SetMarkerColor(kRed);
  pt1A->SetLineColor(kRed);
  pt1B->Scale(1./av);
  // pt1B->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  // pt1B->SetMinimum(0.8);
  // pt1B->SetMaximum(1.2);
  pt1B->SetMarkerStyle(20);
  pt1B->SetMarkerColor(kBlue);
  pt1B->SetLineColor(kBlue);
  gPad->SetGrid(1,1);
  pt1A->Draw();
  pt1B->Draw("same");


  c->cd(2);
  ptbin = 4;
  pt2A = qA->ProjectionY("pt2A",ptbin,ptbin);
  pt2B = qB->ProjectionY("pt2B",ptbin,ptbin);
  hold = (TH1D *) pt2B->Clone("hold");
  for(int i = 1; i<=12; i++) {
    pt2B->SetBinContent(i,hold->GetBinContent(13-i));
    pt2B->SetBinError(i,hold->GetBinError(13-i));
  }
  hold->Delete();
  av = 0;
  for(int i = 1; i<=12; i++) av+=pt2A->GetBinContent(i);
  for(int i = 1; i<=12; i++) av+=pt2B->GetBinContent(i);
  av/=24;
  pt2A->Scale(1./av);
  pt2A->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  pt2A->SetMinimum(0.8);
  pt2A->SetMaximum(1.2);
  pt2A->SetMarkerStyle(20);
  pt2A->SetMarkerColor(kRed);
  pt2A->SetLineColor(kRed);
  pt2B->Scale(1./av);
  // pt2B->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  // pt2B->SetMinimum(0.8);
  // pt2B->SetMaximum(1.2);
  pt2B->SetMarkerStyle(20);
  pt2B->SetMarkerColor(kBlue);
  pt2B->SetLineColor(kBlue);
  gPad->SetGrid(1,1);
  pt2A->Draw();
  pt2B->Draw("same");

  c->cd(3);
  ptbin = 6;
  pt3A = qA->ProjectionY("pt3A",ptbin,ptbin);
  pt3B = qB->ProjectionY("pt3B",ptbin,ptbin);
  hold = (TH1D *) pt3B->Clone("hold");
  for(int i = 1; i<=12; i++) {
    pt3B->SetBinContent(i,hold->GetBinContent(13-i));
    pt3B->SetBinError(i,hold->GetBinError(13-i));
  }
  hold->Delete();
  av = 0;
  for(int i = 1; i<=12; i++) av+=pt3A->GetBinContent(i);
  for(int i = 1; i<=12; i++) av+=pt3B->GetBinContent(i);
  av/=24;
  pt3A->Scale(1./av);
  pt3A->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  pt3A->SetMinimum(0.8);
  pt3A->SetMaximum(1.2);
  pt3A->SetMarkerStyle(20);
  pt3A->SetMarkerColor(kRed);
  pt3A->SetLineColor(kRed);
  pt3B->Scale(1./av);
  // pt3B->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  // pt3B->SetMinimum(0.8);
  // pt3B->SetMaximum(1.2);
  pt3B->SetMarkerStyle(20);
  pt3B->SetMarkerColor(kBlue);
  pt3B->SetLineColor(kBlue);
  gPad->SetGrid(1,1);
  pt3A->Draw();
  pt3B->Draw("same");

  c->cd(4);
  ptbin = 8;
  pt4A = qA->ProjectionY("pt4A",ptbin,ptbin);
  pt4B = qB->ProjectionY("pt4B",ptbin,ptbin);
  hold = (TH1D *) pt4B->Clone("hold");
  for(int i = 1; i<=12; i++) {
    pt4B->SetBinContent(i,hold->GetBinContent(13-i));
    pt4B->SetBinError(i,hold->GetBinError(13-i));
  }
  hold->Delete();
  av = 0;
  for(int i = 1; i<=12; i++) av+=pt4A->GetBinContent(i);
  for(int i = 1; i<=12; i++) av+=pt4B->GetBinContent(i);
  av/=24;
  pt4A->Scale(1./av);
  pt4A->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  pt4A->SetMinimum(0.8);
  pt4A->SetMaximum(1.2);
  pt4A->SetMarkerStyle(20);
  pt4A->SetMarkerColor(kRed);
  pt4A->SetLineColor(kRed);
  pt4B->Scale(1./av);
  // pt4B->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  // pt4B->SetMinimum(0.8);
  // pt4B->SetMaximum(1.2);
  pt4B->SetMarkerStyle(20);
  pt4B->SetMarkerColor(kBlue);
  pt4B->SetLineColor(kBlue);
  gPad->SetGrid(1,1);
  pt4A->Draw();
  pt4B->Draw("same");

  c->cd(5);
  ptbin = 10;
  pt5A = qA->ProjectionY("pt5A",ptbin,ptbin);
  pt5B = qB->ProjectionY("pt5B",ptbin,ptbin);
  hold = (TH1D *) pt5B->Clone("hold");
  for(int i = 1; i<=12; i++) {
    pt5B->SetBinContent(i,hold->GetBinContent(13-i));
    pt5B->SetBinError(i,hold->GetBinError(13-i));
  }
  hold->Delete();
  av = 0;
  for(int i = 1; i<=12; i++) av+=pt5A->GetBinContent(i);
  for(int i = 1; i<=12; i++) av+=pt5B->GetBinContent(i);
  av/=24;
  pt5A->Scale(1./av);
  pt5A->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  pt5A->SetMinimum(0.8);
  pt5A->SetMaximum(1.2);
  pt5A->SetMarkerStyle(20);
  pt5A->SetMarkerColor(kRed);
  pt5A->SetLineColor(kRed);
  pt5B->Scale(1./av);
  // pt5B->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  // pt5B->SetMinimum(0.8);
  // pt5B->SetMaximum(1.2);
  pt5B->SetMarkerStyle(20);
  pt5B->SetMarkerColor(kBlue);
  pt5B->SetLineColor(kBlue);
  gPad->SetGrid(1,1);
  pt5A->Draw();
  pt5B->Draw("same");

  c->cd(6);
  ptbin = 12;
  pt6A = qA->ProjectionY("pt6A",ptbin,ptbin);
  pt6B = qB->ProjectionY("pt6B",ptbin,ptbin);
  hold = (TH1D *) pt6B->Clone("hold");
  for(int i = 1; i<=12; i++) {
    pt6B->SetBinContent(i,hold->GetBinContent(13-i));
    pt6B->SetBinError(i,hold->GetBinError(13-i));
  }
  hold->Delete();
  av = 0;
  for(int i = 1; i<=12; i++) av+=pt6A->GetBinContent(i);
  for(int i = 1; i<=12; i++) av+=pt6B->GetBinContent(i);
  av/=24;
  pt6A->Scale(1./av);
  pt6A->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  pt6A->SetMinimum(0.8);
  pt6A->SetMaximum(1.2);
  pt6A->SetMarkerStyle(20);
  pt6A->SetMarkerColor(kRed);
  pt6A->SetLineColor(kRed);
  pt6B->Scale(1./av);
  // pt6B->GetYaxis()->SetTitle(Form("v_{n}^{obs} (%4.1f - %4.1f GeV/c)",qA->GetXaxis()->GetBinLowEdge(ptbin),qA->GetXaxis()->GetBinLowEdge(ptbin+1)));
  // pt6B->SetMinimum(0.8);
  // pt6B->SetMaximum(1.2);
  pt6B->SetMarkerStyle(20);
  pt6B->SetMarkerColor(kBlue);
  pt6B->SetLineColor(kBlue);
  gPad->SetGrid(1,1);
  pt6A->Draw();
  pt6B->Draw("same");
}
