void OffsetCorrection() {
  double max = 0.05;
  double min = -0.05;
  TCanvas * c = new TCanvas("c","c",1200,1000);
  c->Divide(2,2);
  TFile * foff = new TFile("../offset_PbPb2015_263231_263359.root","read");
  TH2D * hx = (TH2D *) foff->Get("wqxtrk_2_0");
  hx->GetXaxis()->SetRange(1,16);
  c->cd(1);
  gPad->SetTopMargin(0.1);
  gPad->SetRightMargin(0.15);
  hx->SetMaximum(max);
  hx->SetMinimum(min);
  TLatex * lx = new TLatex(0.5,2.6,"<q_{2x}> (0 - 5%) correction");
  lx->SetTextFont(43);
  lx->SetTextSize(28);
  hx->Draw("colz");
  lx->Draw();
  TH2D * hy = (TH2D *) foff->Get("wqytrk_2_0");
  hy->SetMaximum(max);
  hy->SetMinimum(min);
  hy->GetXaxis()->SetRange(1,16);
  hy->SetTitle("<qy> correction");
  c->cd(2);
  gPad->SetTopMargin(0.1);
  gPad->SetRightMargin(0.15);
  TLatex * ly = new TLatex(0.5,2.6,"<q_{2y}> (0 - 5%) correction");
  ly->SetTextFont(43);
  ly->SetTextSize(28);
  hy->Draw("colz");
  ly->Draw();
  TFile * tf2 = new TFile("../MH.root","read");
  TH2D * qcnt = (TH2D *) tf2->Get("vnanalyzer/Harmonics/0_5/qxcnt");

  c->cd(3);
  TH2D * hxf = (TH2D *) tf2->Get("vnanalyzer/Harmonics/0_5/qxav2");
  hxf->Divide(qcnt);
  hxf->GetXaxis()->SetRange(1,16);
  hxf->SetMaximum(max);
  hxf->SetMinimum(min);
  hxf->SetXTitle("p_{T} (GeV/c)");
  hxf->SetYTitle("#eta");
  TLatex * lxf = new TLatex(0.5,2.6,"<q_{2x}> (0-5%) after correction");
  lxf->SetTextFont(43);
  lxf->SetTextSize(28);
  gPad->SetTopMargin(0.1);
  gPad->SetRightMargin(0.15);
  hxf->Draw("colz");
  lxf->Draw();


  c->cd(4);
  TH2D * hyf = (TH2D *) tf2->Get("vnanalyzer/Harmonics/0_5/qyav2");
  hyf->Divide(qcnt);
  hyf->GetXaxis()->SetRange(1,16);
  hyf->SetMaximum(max);
  hyf->SetMinimum(min);
  hyf->SetXTitle("p_{T} (GeV/c)");
  hyf->SetYTitle("#eta");
  TLatex * lyf = new TLatex(0.5,2.6,"<q_{2y}> (0-5%) after correction");
  lyf->SetTextFont(43);
  lyf->SetTextSize(28);
  gPad->SetTopMargin(0.1);
  gPad->SetRightMargin(0.15);
  hyf->Draw("colz");
  lyf->Draw();
  gPad->Update();
TPaletteAxis *palette = (TPaletteAxis*)hyf->GetListOfFunctions()->FindObject("palette");
 // cout<<palette<<endl;
 // c->cd(0);

 // palette->SetX1NDC(-0.2);
 // palette->SetY1NDC(0.5);
 // palette->SetX2NDC(0.05);
 // palette->SetY2NDC(1.5);
 // palette->Draw();
 // c->Update();
 c->Print("recenterChk.pdf","pdf");
}
