void WithAndWithoutDoIt(string cent, string hf, int minetabin, int maxetabin,TH1D *& retwith, TH1D *& retwithout){
  string newcent = cent;
  newcent.replace(newcent.find("_"),1,"-");
  TFile * fwith = new TFile(Form("../results/v2ep/results/results_trackmid2/2015_N2SUB3/PbPb_2015_N2SUB3_v2_%s.root",hf.data()));
  TFile * fwithout = new TFile(Form("../results/v2ep_nocorr/results/results_trackmid2/2015_N2SUB3/PbPb_2015_N2SUB3_v2_%s.root",hf.data()));
  TH2D * h2with = (TH2D *) fwith->Get(Form("%s/epVn",cent.data()));
  TH2D * h2without = (TH2D *) fwithout->Get(Form("%s/epVn",cent.data()));
  TH2D * r = (TH2D *)h2without->Clone("r");
  r->Divide(h2with);
  TH1D * r1 = (TH1D *) r->ProjectionX("rm1",minetabin,maxetabin);
  r1->Scale(0.5);
  TH1D * psi_with = (TH1D *) fwith->Get(Form("%s/Psi_%s",cent.data(),hf.data()));
  psi_with->SetLineColor(kBlue);
  TH1D * psi_without = (TH1D *) fwithout->Get(Form("%s/Psi_%s",cent.data(),hf.data()));
  psi_without->SetLineColor(kRed);
  TCanvas * c = new TCanvas("c","c",1000,800);
  c->Divide(2,2);
  c->cd(2);
  psi_without->SetYTitle(Form("Counts (%s%c)",newcent.data(),'%'));
  psi_without->SetXTitle("#Psi_{2}");
  psi_without->Draw();  
  psi_with->Draw("same");
  c->cd(3);
  TH1D * hwith = (TH1D *) h2with->ProjectionX("hwith",minetabin,maxetabin);
  TH1D * hwithout = (TH1D *) h2without->ProjectionX("hwithout",minetabin,maxetabin);
  hwith->Scale(0.5);
  hwithout->Scale(0.5);
  hwith->SetLineColor(kBlue);
  hwith->SetMarkerColor(kBlue);
  hwithout->SetLineColor(kRed);
  hwithout->SetMarkerColor(kRed);
  hwith->GetXaxis()->SetRangeUser(0.4,12);
  hwith->SetMinimum(0.0);
  hwith->SetMaximum(0.3);
  hwith->SetYTitle("v_{2}");
  hwith->Draw();
  hwithout->Draw("same");
  c->cd(4);
  r1->GetXaxis()->SetRangeUser(0.4,12);
  r1->SetMinimum(0.9);
  r1->SetMaximum(1.1);
  r1->SetYTitle("v_{2}^{without}/v_{2}^{with}");
  r1->Draw();
  TLine * line = new TLine(0.5,1,12,1);
  line->SetLineStyle(2);
  line->SetLineColor(kBlue);
  line->Draw();
  c->cd(1);
  TPaveText * tp = new TPaveText(0.1,0.5,0.9,0.9);
  tp->SetFillColor(kWhite);
  tp->SetBorderSize(0);
  tp->SetTextFont(43);
  tp->SetTextSize(32);
  tp->AddText("2015 PbPb PromptReco");
  tp->AddText(hf.data());
  tp->AddText(Form("%s%c",newcent.data(),'%'));
  tp->Draw();
  TLegend * leg = new TLegend(0.1,0.2,0.9,0.4);
  leg->SetFillColor(kWhite);
  leg->SetBorderSize(0);
  leg->SetTextFont(43);
  leg->SetTextSize(28);
  leg->AddEntry(hwith,"with recentering","lp");
  leg->AddEntry(hwithout,"without recentring","lp");
  leg->Draw();
  c->Print(Form("figures/%s_%s.pdf",hf.data(),cent.data()),"pdf");
  retwith = (TH1D *) hwith->Clone(Form("With_%s_%s",hf.data(),cent.data()));
  retwithout = (TH1D *) hwithout->Clone(Form("Without_%s_%s",hf.data(),cent.data()));
  retwith->SetDirectory(0);
  retwithout->SetDirectory(0);
  cout<<retwith<<endl;
  //fwith->Close();
  //fwithout->Close();

}
void WithAndWithout(){
  TH1D * hwm;
  TH1D * hwom;
  TH1D * hwp;
  TH1D * hwop;
  WithAndWithoutDoIt("20_25",  "HFm2",7,8,hwm,hwom);
  WithAndWithoutDoIt("20_25",  "HFp2",5,6,hwp,hwop);
  hwm->Divide(hwp);
  hwom->Divide(hwop);
  TCanvas * c2 = new TCanvas("c2","c2",800,600);
  c2->cd();
  hwm->SetMinimum(0.8);
  hwm->SetMaximum(1.2);
  hwm->Draw();
  hwom->Draw("same");
  TLine * line = new TLine(0.5,1,12,1);
  line->SetLineStyle(2);
  line->Draw();
  // WithAndWithoutDoIt("5_10", "HFm2",7,8);
  // WithAndWithoutDoIt("10_15","HFm2",7,8);
  // WithAndWithoutDoIt("15_20","HFm2",7,8);
  // WithAndWithoutDoIt("20_25","HFm2",7,8);
  // WithAndWithoutDoIt("25_30","HFm2",7,8);
  // WithAndWithoutDoIt("30_35","HFm2",7,8);
  // WithAndWithoutDoIt("35_40","HFm2",7,8);
  // WithAndWithoutDoIt("40_50","HFm2",7,8);
  // WithAndWithoutDoIt("50_60","HFm2",7,8);
  // WithAndWithoutDoIt("60_70","HFm2",7,8);

  // WithAndWithoutDoIt("5_10", "HFp2",5,6);
  // WithAndWithoutDoIt("10_15","HFp2",5,6);
  // WithAndWithoutDoIt("15_20","HFp2",5,6);
  // WithAndWithoutDoIt("20_25","HFp2",5,6);
  // WithAndWithoutDoIt("25_30","HFp2",5,6);
  // WithAndWithoutDoIt("30_35","HFp2",5,6);
  // WithAndWithoutDoIt("35_40","HFp2",5,6);
  // WithAndWithoutDoIt("40_50","HFp2",5,6);
  // WithAndWithoutDoIt("50_60","HFp2",5,6);
  // WithAndWithoutDoIt("60_70","HFp2",5,6);
}
